version: '2.4'
services:

  keras-py27-jupyter:
    image: encoredtechr/deepo:keras-py27-jupyter-cudnn7.0
    depends_on:
      - cuda-9-0_cudnn-7-0
    ports:
      - 8888:8888
    environment:
      - HOME=${HOME}
      - JUPYTER_PASSWD=Dlszhdjem
    volumes:
      - ${HOME}:${HOME}
      - ./jupyter-config:${HOME}/.jupyter
    runtime: nvidia
    command: jupyter notebook

  cuda-9-0_cudnn-7-0:
    image: encoredtechr/cuda:9.0-cudnn7.0
