version: '2.4'
services:

  mydeep:
    build:
      context: ./mydeep
    container_name: mydeep
    ports:
      - 8888:8888
      - 6006:6006
    environment:
      - JUPYTER_PASSWD=${JUPYTER_PASSWD}
    volumes:
      - ${HOME}/workspace/:/root/workspace
      - ./jupyter-config:/root/.jupyter
      - /data6:/root/data6
    runtime: nvidia
    command: jupyter lab --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=''
             
